# Geodesic / 반경 내 거리 측정

### Geopy import

In [1]:
pip install geopy

Requirement already satisfied: geopy in /Users/angela/opt/anaconda3/lib/python3.9/site-packages (2.4.0)
Requirement already satisfied: geographiclib<3,>=1.52 in /Users/angela/opt/anaconda3/lib/python3.9/site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from geopy.distance import geodesic
import warnings
warnings.filterwarnings('ignore')

### test

In [3]:
#중심점(상권 중앙정보)
center_point = (37.496837, 127.028104)

points_within_radius = []
radius = 0.3


# flipped_data = [(lat, lon) for lon, lat in data]

data = [(37.49813573, 127.0291478),(37.4988294, 127.0298391), (37.50235998, 127.0257902)]

In [4]:
for point in data:
    distance = geodesic(center_point, point).kilometers
    
    if distance <= radius:
        points_within_radius.append(point)

for point in points_within_radius:
    print('위도', point[0], '경도', point[1])

위도 37.49813573 경도 127.0291478
위도 37.4988294 경도 127.0298391

### 지하철 데이터

In [5]:
import pandas as pd

subway = pd.read_csv('./최종_지하철_3개년_승하차.csv')
subway[:10]

,연도,분기,월,지하철역,호선명,00-06시,06-11시,11-14시,14-17시,17-21시,21-24시,위도,경도
0,2020,1,1,강남,2호선,64195,1390569,851787,1020723,1842601,807774,127.028008,37.497414
1,2020,1,1,삼성(무역센터),2호선,20837,968174,439256,553549,1077187,279793,127.063160,37.508844
2,2020,1,1,선릉,2호선,23811,891141,372616,472332,898156,267683,127.048505,37.504571
3,2020,1,1,역삼,2호선,20816,1001912,343193,410819,900137,237617,127.036456,37.500622
4,2020,1,1,대청,3호선,8088,163454,74159,87450,159204,55764,127.079532,37.493514
5,2020,1,1,대치,3호선,6509,187050,111787,122559,198688,93025,127.063642,37.494612
6,2020,1,1,도곡,3호선,3672,101095,48639,51538,90531,26194,127.055319,37.491073
7,2020,1,1,매봉,3호선,4054,209435,79220,92194,195911,53893,127.046769,37.486947
8,2020,1,1,수서,3호선,12612,304169,162286,179818,310014,102146,127.101664,37.487425
9,2020,1,1,신사,3호선,14256,461758,282175,357447,647566,218499,127.020114,37.516334

In [6]:
subway.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1152 entries, 0 to 1151
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      1152 non-null   int64
 1   분기      1152 non-null   int64
 2   월       1152 non-null   int64
 3   지하철역    1152 non-null   object
 4   호선명     1152 non-null   object
 5   00-06시  1152 non-null   int64
 6   06-11시  1152 non-null   int64
 7   11-14시  1152 non-null   int64
 8   14-17시  1152 non-null   int64
 9   17-21시  1152 non-null   int64
 10  21-24시  1152 non-null   int64
 11  위도      1152 non-null   float64
 12  경도      1152 non-null   float64
dtypes: float64(2), int64(9), object(2)
memory usage: 117.1+ KB

In [7]:
sub_position_list = list(zip(subway['경도'], subway['위도']))
sub_position_list[:10]

[(37.4974135, 127.028008),
 (37.508844, 127.06316),
 (37.504571, 127.048505),
 (37.500622, 127.036456),
 (37.493514, 127.079532),
 (37.494612, 127.063642),
 (37.491073, 127.055319),
 (37.486947, 127.046769),
 (37.487425, 127.1016645),
 (37.516334, 127.020114)]

In [8]:
# subway['위경도'] = '(' + subway['경도'].astype(str) + ',' + subway['위도'].astype(str) + ')'
# subway.head()

### 버스 데이터

In [9]:
bus = pd.read_csv('./최종_버스데이터+버스정류장_위경도_값(Bus_Points).csv')
bus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6236 entries, 0 to 6235
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   연도             6236 non-null   int64
 1   분기             6236 non-null   object
 2   버스정류장ARS번호     6236 non-null   int64
 3   00~06_승하차_승객수  6236 non-null   int64
 4   06~11_승하차_승객수  6236 non-null   int64
 5   11~14_승하차_승객수  6236 non-null   int64
 6   14~17_승하차_승객수  6236 non-null   int64
 7   17~21_승하차_승객수  6236 non-null   int64
 8   21~24_승하차_승객수  6236 non-null   int64
 9   X좌표            6225 non-null   float64
 10  Y좌표            6225 non-null   float64
 11  버스정류장_위경도_값    6236 non-null   object
dtypes: float64(2), int64(8), object(2)
memory usage: 584.8+ KB

In [10]:
bus = bus[bus['X좌표'].notnull()]
bus.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6225 entries, 0 to 6235
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   연도             6225 non-null   int64
 1   분기             6225 non-null   object
 2   버스정류장ARS번호     6225 non-null   int64
 3   00~06_승하차_승객수  6225 non-null   int64
 4   06~11_승하차_승객수  6225 non-null   int64
 5   11~14_승하차_승객수  6225 non-null   int64
 6   14~17_승하차_승객수  6225 non-null   int64
 7   17~21_승하차_승객수  6225 non-null   int64
 8   21~24_승하차_승객수  6225 non-null   int64
 9   X좌표            6225 non-null   float64
 10  Y좌표            6225 non-null   float64
 11  버스정류장_위경도_값    6225 non-null   object
dtypes: float64(2), int64(8), object(2)
memory usage: 632.2+ KB

In [11]:
bus_position_list = list(zip(bus['Y좌표'], bus['X좌표']))
bus_position_list[:2]
# bus.head(2)

[(37.52299569, 127.0204417), (37.52299569, 127.0204417)]

### 상권 센터포인트

In [12]:
market_points = pd.read_csv('./총합본(Center_Points).csv')

market_points.head(2)

,기준_년_코드,기준_분기_코드,상권_코드,점포수,시간대_00~06_매출_금액_평균,시간대_06~11_매출_금액_평균,시간대_11~14_매출_금액_평균,시간대_14~17_매출_금액_평균,시간대_17~21_매출_금액_평균,시간대_21~24_매출_금액_평균,...,수요일_생활인구_수,목요일_생활인구_수,금요일_생활인구_수,토요일_생활인구_수,일요일_생활인구_수,엑스좌표_값,와이좌표_값,시군구_코드,폴리곤_좌표,상권_중앙위경도_값
0,2020,1,2110949,6,125163.150183,217164.879121,256343.263736,217222.536630,304378.824176,222872.315018,...,58948,59700,60271,52877,47711,201717,446819,11680,"POLYGON ((201834.4006 446766.3146, 201863.6311...","37.520855545263544, 127.01942289119167"
1,2020,1,2110951,3,94688.223443,66467.593407,80462.010989,87369.399267,188897.897436,155364.446886,...,88383,89759,89112,74083,66223,202246,446821,11680,"POLYGON ((202191.9843 446916.686100001, 202201...","37.52087242965624, 127.02540700249948"

In [13]:
market_points[['위도', '경도']] = market_points['상권_중앙위경도_값'].str.split(', ', expand=True)
market_points[['위도', '경도']] = market_points[['위도', '경도']].astype(float)
market_points_list = list(zip(market_points['위도'], market_points['경도']))

In [14]:
market_points_list[:3]

[(37.520855545263544, 127.01942289119167),
 (37.52087242965624, 127.02540700249948),
 (37.5113305986889, 127.02633124285852)]

In [15]:
market_points[:3]

,기준_년_코드,기준_분기_코드,상권_코드,점포수,시간대_00~06_매출_금액_평균,시간대_06~11_매출_금액_평균,시간대_11~14_매출_금액_평균,시간대_14~17_매출_금액_평균,시간대_17~21_매출_금액_평균,시간대_21~24_매출_금액_평균,...,금요일_생활인구_수,토요일_생활인구_수,일요일_생활인구_수,엑스좌표_값,와이좌표_값,시군구_코드,폴리곤_좌표,상권_중앙위경도_값,위도,경도
0,2020,1,2110949,6,125163.150183,217164.879121,256343.263736,217222.536630,304378.824176,222872.315018,...,60271,52877,47711,201717,446819,11680,"POLYGON ((201834.4006 446766.3146, 201863.6311...","37.520855545263544, 127.01942289119167",37.520856,127.019423
1,2020,1,2110951,3,94688.223443,66467.593407,80462.010989,87369.399267,188897.897436,155364.446886,...,89112,74083,66223,202246,446821,11680,"POLYGON ((202191.9843 446916.686100001, 202201...","37.52087242965624, 127.02540700249948",37.520872,127.025407
2,2020,1,2110952,3,177736.461538,127178.919414,105252.366300,103031.025641,217967.512821,173673.849817,...,33613,32730,33196,202328,445762,11680,"POLYGON ((202403.3906 445735.6132, 202362.1278...","37.5113305986889, 127.02633124285852",37.511331,127.026331

### 테스트 코드

In [16]:
# 중심점(상권 중앙정보) => 리스트로
center_points = (37.496837, 127.028104)

# 반경 몇 미터(meters)/킬로미터(kilometers)인지 지정
radius = 300

# 반경 내에 있는 지점의 위치 정보 list
points_within_radius = []

# 위치를 확인할 데이터(버스정류장, 지하철역 - 위도+경도)
points = [(37.49813573, 127.0291478),(37.4988294, 127.0298391), (37.50235998, 127.0257902)]

for point in points:
    distance = geodesic(center_points, point).meters
    
    if distance <= radius:
        points_within_radius.append(point)

print('-----------반경 내에 있는 지점-------------------')
for point in points_within_radius:
    print(f'[위도]{point[0]}, [경도]{point[1]}')

-----------반경 내에 있는 지점-------------------
[위도]37.49813573, [경도]127.0291478
[위도]37.4988294, [경도]127.0298391

In [17]:
print(market_points_list[:3])
print(sub_position_list[:3])
print(bus_position_list[:3])

[(37.520855545263544, 127.01942289119167), (37.52087242965624, 127.02540700249948), (37.5113305986889, 127.02633124285852)]
[(37.4974135, 127.028008), (37.508844, 127.06316), (37.504571, 127.048505)]
[(37.52299569, 127.0204417), (37.52299569, 127.0204417), (37.52299569, 127.0204417)]

In [18]:
# 상권별로 n미터내에 몇개의 지하철역이 있는가?
# 결과 : 00상권 ---- 지하철역 00개

# 상권코드 중앙
centerpoints = market_points_list

#상권 반경 00미터
radius = 500

# 반경별 리스트
# bus_within_radius = []
# subway_within_radius = []

subway_stations = sub_position_list
bus_stations = bus_position_list

result = {}

for center in centerpoints:
    bus_count = 0
    subway_count = 0
    
    #버스정류장
    for bus in bus_stations:
        distance = geodesic(center, bus).meters
        if distance <= radius:
            bus_count += 1

    
    #지하철역
    for subway in subway_stations:
        distance = geodesic(center, subway).meters
        if distance <= radius:
            subway_count += 1
    
    #결과를 딕셔너리에 저장
    result[center] = [subway_count, bus_count]

# 결과 출력
for center, counts in result.items():
    print(f'{center} 상권 ---- 지하철역 {counts[0]}개, 버스 정류장 {counts[1]}개')

(37.520855545263544, 127.01942289119167) 상권 ---- 지하철역 0개, 버스 정류장 64개
(37.52087242965624, 127.02540700249948) 상권 ---- 지하철역 0개, 버스 정류장 140개
(37.5113305986889, 127.02633124285852) 상권 ---- 지하철역 36개, 버스 정류장 60개
(37.50250921505765, 127.02866917807879) 상권 ---- 지하철역 36개, 버스 정류장 97개
(37.50909540147428, 127.02932769615451) 상권 ---- 지하철역 36개, 버스 정류장 72개
(37.51779849799859, 127.03166130118623) 상권 ---- 지하철역 36개, 버스 정류장 168개
(37.5032290671925, 127.03235633361939) 상권 ---- 지하철역 72개, 버스 정류장 96개
(37.525411777447985, 127.03237722460005) 상권 ---- 지하철역 36개, 버스 정류장 152개
(37.487334822600594, 127.03407945616239) 상권 ---- 지하철역 0개, 버스 정류장 96개
(37.511076260927844, 127.03433908142084) 상권 ---- 지하철역 72개, 버스 정류장 156개
(37.49237962946542, 127.03686347002896) 상권 ---- 지하철역 0개, 버스 정류장 148개
(37.5062728314113, 127.03785426242342) 상권 ---- 지하철역 36개, 버스 정류장 156개
(37.51878774810336, 127.03795107793988) 상권 ---- 지하철역 72개, 버스 정류장 204개
(37.50439861327024, 127.03824915298691) 상권 ---- 지하철역 36개, 버스 정류장 156개
(37.507217264689004, 127.04261627038929) 상권 ---- 지하철역 72개, 버스 정류장 148개
(37.494594100718025, 127.04281264335714) 상권 ---- 지하철역 0개, 버스 정류장 276개
(37.51359558431378, 127.04475767819501) 상권 ---- 지하철역 72개, 버스 정류장 156개
(37.48725902172483, 127.04517162847172) 상권 ---- 지하철역 36개, 버스 정류장 190개
(37.52171331120836, 127.04557700798111) 상권 ---- 지하철역 0개, 버스 정류장 108개
(37.477338239228565, 127.04690671040551) 상권 ---- 지하철역 0개, 버스 정류장 173개
(37.4808246207884, 127.04820908778728) 상권 ---- 지하철역 0개, 버스 정류장 253개
(37.47550836944001, 127.04892921001091) 상권 ---- 지하철역 0개, 버스 정류장 225개
(37.47772434054866, 127.05015165991955) 상권 ---- 지하철역 0개, 버스 정류장 252개
(37.4736959569425, 127.05216125750721) 상권 ---- 지하철역 0개, 버스 정류장 149개
(37.523026010525676, 127.0522521435632) 상권 ---- 지하철역 36개, 버스 정류장 152개
(37.51816864142927, 127.05438666812174) 상권 ---- 지하철역 36개, 버스 정류장 144개
(37.50279748516958, 127.05443206338535) 상권 ---- 지하철역 0개, 버스 정류장 216개
(37.4999043020278, 127.05646557351078) 상권 ---- 지하철역 0개, 버스 정류장 228개
(37.48313403328187, 127.0615182258128) 상권 ---- 지하철역 36개, 버스 정류장 220개
(37.51722762128031, 127.06242850425231) 상권 ---- 지하철역 36개, 버스 정류장 100개
(37.50178366723011, 127.06380667872182) 상권 ---- 지하철역 0개, 버스 정류장 184개
(37.49220195577839, 127.08454831021591) 상권 ---- 지하철역 36개, 버스 정류장 297개
(37.471724786298864, 127.10370931049309) 상권 ---- 지하철역 0개, 버스 정류장 197개
(37.46366702265568, 127.10677272709853) 상권 ---- 지하철역 0개, 버스 정류장 170개
(37.469565171958735, 127.11979244528801) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.510691750707316, 127.02211217405002) 상권 ---- 지하철역 36개, 버스 정류장 40개
(37.52086399195278, 127.02259028422475) 상권 ---- 지하철역 0개, 버스 정류장 84개
(37.50496965911973, 127.02562780655029) 상권 ---- 지하철역 36개, 버스 정류장 60개
(37.525611170385595, 127.02777299030016) 상권 ---- 지하철역 36개, 버스 정류장 112개
(37.51978156581801, 127.02826855511489) 상권 ---- 지하철역 0개, 버스 정류장 96개
(37.513573344814894, 127.02952173545057) 상권 ---- 지하철역 36개, 버스 정류장 92개
(37.49028196786674, 127.0309938485395) 상권 ---- 지하철역 0개, 버스 정류장 74개
(37.521302871685855, 127.0335745396856) 상권 ---- 지하철역 0개, 버스 정류장 120개
(37.50773372300574, 127.03368156281698) 상권 ---- 지하철역 36개, 버스 정류장 168개
(37.527294390847324, 127.0340863134583) 상권 ---- 지하철역 36개, 버스 정류장 136개
(37.51520256206142, 127.03534767368451) 상권 ---- 지하철역 36개, 버스 정류장 180개
(37.50034474708441, 127.03615491755498) 상권 ---- 지하철역 36개, 버스 정류장 96개
(37.49537078733338, 127.03745296989744) 상권 ---- 지하철역 0개, 버스 정류장 132개
(37.50852500535553, 127.03889594244671) 상권 ---- 지하철역 108개, 버스 정류장 216개
(37.522895842647785, 127.03941246043162) 상권 ---- 지하철역 0개, 버스 정류장 120개
(37.49226149114439, 127.03996174769397) 상권 ---- 지하철역 0개, 버스 정류장 168개
(37.526832962629484, 127.04018381643365) 상권 ---- 지하철역 36개, 버스 정류장 120개
(37.51636317318784, 127.04058541332707) 상권 ---- 지하철역 72개, 버스 정류장 176개
(37.502793223157454, 127.0429077996716) 상권 ---- 지하철역 0개, 버스 정류장 96개
(37.48390785799115, 127.04360930895815) 상권 ---- 지하철역 36개, 버스 정류장 142개
(37.49723356283846, 127.04413724979848) 상권 ---- 지하철역 0개, 버스 정류장 260개
(37.511405894352244, 127.04541239018845) 상권 ---- 지하철역 72개, 버스 정류장 120개
(37.52461358412792, 127.04798837218263) 상권 ---- 지하철역 0개, 버스 정류장 112개
(37.51854045610646, 127.04888942339811) 상권 ---- 지하철역 36개, 버스 정류장 116개
(37.50458384746136, 127.04901603682542) 상권 ---- 지하철역 72개, 버스 정류장 156개
(37.50054579641033, 127.05260967286942) 상권 ---- 지하철역 36개, 버스 정류장 204개
(37.497202550317624, 127.05374948985842) 상권 ---- 지하철역 36개, 버스 정류장 180개
(37.51216823841516, 127.05377153085408) 상권 ---- 지하철역 36개, 버스 정류장 96개
(37.524259282338384, 127.05468521734747) 상권 ---- 지하철역 0개, 버스 정류장 84개
(37.506770010092765, 127.05636895451428) 상권 ---- 지하철역 0개, 버스 정류장 172개
(37.52086161406612, 127.05657185968903) 상권 ---- 지하철역 36개, 버스 정류장 108개
(37.50320129220644, 127.05789304626857) 상권 ---- 지하철역 0개, 버스 정류장 144개
(37.5120485682594, 127.0590875108244) 상권 ---- 지하철역 36개, 버스 정류장 204개
(37.49901935242015, 127.06043430040828) 상권 ---- 지하철역 0개, 버스 정류장 136개
(37.49452251741251, 127.06200250745094) 상권 ---- 지하철역 36개, 버스 정류장 156개
(37.51483114367817, 127.06206454963771) 상권 ---- 지하철역 36개, 버스 정류장 152개
(37.509280590059866, 127.0627611960508) 상권 ---- 지하철역 36개, 버스 정류장 204개
(37.504260852229244, 127.06487188953616) 상권 ---- 지하철역 0개, 버스 정류장 156개
(37.48780855534486, 127.10283827879296) 상권 ---- 지하철역 72개, 버스 정류장 168개
(37.509033503693814, 127.02414754331555) 상권 ---- 지하철역 72개, 버스 정류장 64개
(37.48880703177452, 127.06765141951202) 상권 ---- 지하철역 36개, 버스 정류장 224개
(37.511002913176945, 127.06005939988393) 상권 ---- 지하철역 72개, 버스 정류장 256개
(37.515026175047964, 127.04976940660319) 상권 ---- 지하철역 36개, 버스 정류장 108개

In [21]:
# 상권별로 n미터내에 몇개의 지하철역이 있는가?
# 결과 : 00상권 ---- 지하철역 00개

# 상권코드 중앙
centerpoints = market_points_list

#상권 반경 00미터
radius = 0.3

# 반경별 리스트
# bus_within_radius = []
# subway_within_radius = []

subway_stations = sub_position_list
bus_stations = bus_position_list

result = {}

for center in centerpoints:
    bus_count = 0
    subway_count = 0
    
    #버스정류장
    for bus in bus_stations:
        distance = geodesic(center, bus).kilometers
        if distance <= radius:
            bus_count += 1

    
    #지하철역
    for subway in subway_stations:
        distance = geodesic(center, subway).kilometers
        if distance <= radius:
            subway_count += 1
    
    #결과를 딕셔너리에 저장
    result[center] = [subway_count, bus_count]

# 결과 출력
for center, counts in result.items():
    print(f'{center} 상권 ---- 지하철역 {counts[0]}개, 버스 정류장 {counts[1]}개')

(37.520855545263544, 127.01942289119167) 상권 ---- 지하철역 0개, 버스 정류장 12개
(37.52087242965624, 127.02540700249948) 상권 ---- 지하철역 0개, 버스 정류장 24개
(37.5113305986889, 127.02633124285852) 상권 ---- 지하철역 0개, 버스 정류장 12개
(37.50250921505765, 127.02866917807879) 상권 ---- 지하철역 0개, 버스 정류장 24개
(37.50909540147428, 127.02932769615451) 상권 ---- 지하철역 0개, 버스 정류장 12개
(37.51779849799859, 127.03166130118623) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.5032290671925, 127.03235633361939) 상권 ---- 지하철역 0개, 버스 정류장 0개
(37.525411777447985, 127.03237722460005) 상권 ---- 지하철역 0개, 버스 정류장 24개
(37.487334822600594, 127.03407945616239) 상권 ---- 지하철역 0개, 버스 정류장 20개
(37.511076260927844, 127.03433908142084) 상권 ---- 지하철역 0개, 버스 정류장 68개
(37.49237962946542, 127.03686347002896) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.5062728314113, 127.03785426242342) 상권 ---- 지하철역 0개, 버스 정류장 56개
(37.51878774810336, 127.03795107793988) 상권 ---- 지하철역 0개, 버스 정류장 64개
(37.50439861327024, 127.03824915298691) 상권 ---- 지하철역 0개, 버스 정류장 12개
(37.507217264689004, 127.04261627038929) 상권 ---- 지하철역 0개, 버스 정류장 68개
(37.494594100718025, 127.04281264335714) 상권 ---- 지하철역 0개, 버스 정류장 116개
(37.51359558431378, 127.04475767819501) 상권 ---- 지하철역 0개, 버스 정류장 24개
(37.48725902172483, 127.04517162847172) 상권 ---- 지하철역 36개, 버스 정류장 41개
(37.52171331120836, 127.04557700798111) 상권 ---- 지하철역 0개, 버스 정류장 48개
(37.477338239228565, 127.04690671040551) 상권 ---- 지하철역 0개, 버스 정류장 132개
(37.4808246207884, 127.04820908778728) 상권 ---- 지하철역 0개, 버스 정류장 76개
(37.47550836944001, 127.04892921001091) 상권 ---- 지하철역 0개, 버스 정류장 53개
(37.47772434054866, 127.05015165991955) 상권 ---- 지하철역 0개, 버스 정류장 113개
(37.4736959569425, 127.05216125750721) 상권 ---- 지하철역 0개, 버스 정류장 69개
(37.523026010525676, 127.0522521435632) 상권 ---- 지하철역 0개, 버스 정류장 20개
(37.51816864142927, 127.05438666812174) 상권 ---- 지하철역 36개, 버스 정류장 48개
(37.50279748516958, 127.05443206338535) 상권 ---- 지하철역 0개, 버스 정류장 24개
(37.4999043020278, 127.05646557351078) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.48313403328187, 127.0615182258128) 상권 ---- 지하철역 0개, 버스 정류장 80개
(37.51722762128031, 127.06242850425231) 상권 ---- 지하철역 0개, 버스 정류장 12개
(37.50178366723011, 127.06380667872182) 상권 ---- 지하철역 0개, 버스 정류장 60개
(37.49220195577839, 127.08454831021591) 상권 ---- 지하철역 0개, 버스 정류장 115개
(37.471724786298864, 127.10370931049309) 상권 ---- 지하철역 0개, 버스 정류장 64개
(37.46366702265568, 127.10677272709853) 상권 ---- 지하철역 0개, 버스 정류장 88개
(37.469565171958735, 127.11979244528801) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.510691750707316, 127.02211217405002) 상권 ---- 지하철역 36개, 버스 정류장 36개
(37.52086399195278, 127.02259028422475) 상권 ---- 지하철역 0개, 버스 정류장 8개
(37.50496965911973, 127.02562780655029) 상권 ---- 지하철역 36개, 버스 정류장 48개
(37.525611170385595, 127.02777299030016) 상권 ---- 지하철역 36개, 버스 정류장 72개
(37.51978156581801, 127.02826855511489) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.513573344814894, 127.02952173545057) 상권 ---- 지하철역 36개, 버스 정류장 60개
(37.49028196786674, 127.0309938485395) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.521302871685855, 127.0335745396856) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.50773372300574, 127.03368156281698) 상권 ---- 지하철역 36개, 버스 정류장 96개
(37.527294390847324, 127.0340863134583) 상권 ---- 지하철역 0개, 버스 정류장 68개
(37.51520256206142, 127.03534767368451) 상권 ---- 지하철역 0개, 버스 정류장 84개
(37.50034474708441, 127.03615491755498) 상권 ---- 지하철역 36개, 버스 정류장 84개
(37.49537078733338, 127.03745296989744) 상권 ---- 지하철역 0개, 버스 정류장 48개
(37.50852500535553, 127.03889594244671) 상권 ---- 지하철역 0개, 버스 정류장 60개
(37.522895842647785, 127.03941246043162) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.49226149114439, 127.03996174769397) 상권 ---- 지하철역 0개, 버스 정류장 108개
(37.526832962629484, 127.04018381643365) 상권 ---- 지하철역 36개, 버스 정류장 48개
(37.51636317318784, 127.04058541332707) 상권 ---- 지하철역 72개, 버스 정류장 96개
(37.502793223157454, 127.0429077996716) 상권 ---- 지하철역 0개, 버스 정류장 48개
(37.48390785799115, 127.04360930895815) 상권 ---- 지하철역 0개, 버스 정류장 106개
(37.49723356283846, 127.04413724979848) 상권 ---- 지하철역 0개, 버스 정류장 108개
(37.511405894352244, 127.04541239018845) 상권 ---- 지하철역 72개, 버스 정류장 100개
(37.52461358412792, 127.04798837218263) 상권 ---- 지하철역 0개, 버스 정류장 36개
(37.51854045610646, 127.04888942339811) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.50458384746136, 127.04901603682542) 상권 ---- 지하철역 72개, 버스 정류장 84개
(37.50054579641033, 127.05260967286942) 상권 ---- 지하철역 0개, 버스 정류장 84개
(37.497202550317624, 127.05374948985842) 상권 ---- 지하철역 36개, 버스 정류장 108개
(37.51216823841516, 127.05377153085408) 상권 ---- 지하철역 36개, 버스 정류장 48개
(37.524259282338384, 127.05468521734747) 상권 ---- 지하철역 0개, 버스 정류장 32개
(37.506770010092765, 127.05636895451428) 상권 ---- 지하철역 0개, 버스 정류장 84개
(37.52086161406612, 127.05657185968903) 상권 ---- 지하철역 0개, 버스 정류장 84개
(37.50320129220644, 127.05789304626857) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.5120485682594, 127.0590875108244) 상권 ---- 지하철역 36개, 버스 정류장 48개
(37.49901935242015, 127.06043430040828) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.49452251741251, 127.06200250745094) 상권 ---- 지하철역 36개, 버스 정류장 76개
(37.51483114367817, 127.06206454963771) 상권 ---- 지하철역 36개, 버스 정류장 88개
(37.509280590059866, 127.0627611960508) 상권 ---- 지하철역 36개, 버스 정류장 152개
(37.504260852229244, 127.06487188953616) 상권 ---- 지하철역 0개, 버스 정류장 48개
(37.48780855534486, 127.10283827879296) 상권 ---- 지하철역 72개, 버스 정류장 144개
(37.509033503693814, 127.02414754331555) 상권 ---- 지하철역 0개, 버스 정류장 24개
(37.48880703177452, 127.06765141951202) 상권 ---- 지하철역 36개, 버스 정류장 136개
(37.511002913176945, 127.06005939988393) 상권 ---- 지하철역 0개, 버스 정류장 72개
(37.515026175047964, 127.04976940660319) 상권 ---- 지하철역 0개, 버스 정류장 36개