## 열린데이터광장 부동산 데이터 >> 12000 페이지까지 데이터 추출, 합치기

In [4]:
import requests
import json
import pandas as pd

SERVICE_KEY = "566468557572733034336b65477a52"
data = None
for j in range(1,13):
    url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+((j-1)*1000)}/{j*1000}'
    # url = f'http://openapi.seoul.go.kr:8088/{service_key}/json/tbLnOpendataRentV/1/1000/2023/11560'
    #print(url)
    req = requests.get(url)
    content = req.json()
    con = content['tbLnOpendataRtmsV']['row']
    result = pd.DataFrame(con)
    data = pd.concat([data, result])
data = data.reset_index(drop=True)
data.head()

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2023,11710,송파구,10800,문정동,1,대지,0652,0004,힐스테이트에코문정,...,20500,20.79,32.68,4.0,,,2018,오피스텔,중개거래,서울 송파구
1,2023,11560,영등포구,10900,영등포동8가,1,대지,0051,0001,메이준,...,8000,17.44,25.56,6.0,,,2012,오피스텔,중개거래,서울 영등포구
2,2023,11380,은평구,10500,구산동,1,대지,0345,0020,솔빛엘르빌,...,22000,49.30,27.73,2.0,,,2012,연립다세대,중개거래,서울 은평구
3,2023,11620,관악구,10100,봉천동,1,대지,1708,0000,두산,...,80000,59.92,0.00,10.0,,,2000,아파트,중개거래,서울 관악구
4,2023,11500,강서구,10300,화곡동,1,대지,1071,0007,와이앤비,...,22500,25.38,15.19,3.0,,,2017,연립다세대,중개거래,서울 강서구